#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from organize_stars import http_json, load_json_file, parse_json_object, read_minimax_env, save_json_file


NEWSNOW_ENDPOINT = "https://newsnow.busiyi.world/api/s/entire"
DEFAULT_SOURCES = [
    "36kr-renqi",
    "baidu",
    "bilibili-hot-search",
    "chongbuluo-hot",
    "cls-hot",
    "coolapk",
    "douban",
    "douyin",
    "freebuf",
    "github-trending-today",
    "hackernews",
    "hupu",
    "ifeng",
    "iqiyi-hot-ranklist",
    "juejin",
    "nowcoder",
    "producthunt",
    "qqvideo-tv-hotsearch",
    "sspai",
    "steam",
    "tencent-hot",
    "thepaper",
    "tieba",
    "toutiao",
    "wallstreetcn-hot",
    "weibo",
    "xueqiu-hotstock",
    "zhihu",
]
MAX_TRENDS = 18
MAX_REPOS = 36
REPO_THEMES = [
    {"keywords": ["seo", "geo", "keyword", "audit", "growth", "ranking"], "limit": 4},
    {"keywords": ["crawl", "scrap", "browser", "playwright", "puppeteer", "extract"], "limit": 4},
    {"keywords": ["claude code", "codex", "cursor", "coding agent", "code intelligence", "developer"], "limit": 4},
    {"keywords": ["video", "voice", "audio", "image", "content", "logo"], "limit": 4},
    {"keywords": ["trading", "quant", "finance", "market", "stock", "polymarket"], "limit": 4},
]
OPPORTUNITY_SYSTEM_PROMPT = """You turn current trend/news signals and a user's starred GitHub repositories into concrete small product opportunities.
Return strict JSON only with this shape:
{
  "ideas": [
    {
      "name": "short product name",
      "summary": "1 sentence",
      "why_now": "1-2 sentences",
      "revenue_model": "how it can make money",
      "build_plan": ["3 short steps"],
      "trends": ["exact trend titles from the provided list"],
      "repos": ["exact owner/repo names from the provided list"],
      "category_focus": ["1-3 short category labels"],
      "confidence": "high or medium or low"
    }
  ]
}
Rules:
- Return 4 ideas.
- Each idea must use at least 2 repositories and at least 1 trend.
- Optimize for fast launch, leverage, and practical passive or semi-passive revenue.
- Prefer products, data services, workflow tools, audits, monitoring, marketplaces, or niche B2B utilities.
- Use only repository names and trend titles that appear in the provided input.
- Keep language concrete and non-hype."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        default="minimax.json",
        help="Path to the MiniMax Anthropic-compatible config file",
    )
    parser.add_argument(
        "--cache",
        default="stars_cache.json",
        help="Path to the stars cache file generated by organize_stars.py",
    )
    parser.add_argument(
        "--output-dir",
        default="opportunities",
        help="Directory for dated opportunity reports",
    )
    parser.add_argument(
        "--date",
        default="",
        help="UTC date override in YYYY-MM-DD format",
    )
    parser.add_argument(
        "--site-dir",
        default="docs",
        help="Directory for generated GitHub Pages assets",
    )
    return parser.parse_args()


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def utc_today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def resolve_path(root: Path, raw_path: str) -> Path:
    path = Path(raw_path)
    return path if path.is_absolute() else (root / path).resolve()


def slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "trend"


def load_starred_repos(cache_path: Path) -> list[dict[str, Any]]:
    cache = load_json_file(cache_path, {"repos": {}})
    repos = cache.get("repos", {}) if isinstance(cache, dict) else {}
    if not isinstance(repos, dict) or not repos:
        raise ValueError(f"Cache file is missing or empty: {cache_path}")
    items = [repo for repo in repos.values() if isinstance(repo, dict)]
    return sorted(items, key=lambda item: int(item.get("stargazers_count") or 0), reverse=True)


def fetch_newsnow_payload() -> list[dict[str, Any]]:
    payload = {"sources": DEFAULT_SOURCES}
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0",
    }
    response, _ = http_json(NEWSNOW_ENDPOINT, headers=headers, payload=payload, timeout=30)
    if not isinstance(response, list):
        raise ValueError("Unexpected NewsNow response format.")
    return response


def format_source_name(source_id: str) -> str:
    parts = [part for part in source_id.replace("_", "-").split("-") if part]
    return " ".join(part.upper() if len(part) <= 3 else part.capitalize() for part in parts)


def dedupe_trends(payload: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    flattened: list[dict[str, Any]] = []
    source_statuses: list[dict[str, Any]] = []
    seen_titles: set[str] = set()
    for source_index, block in enumerate(payload):
        if not isinstance(block, dict):
            continue
        source_id = str(block.get("id") or f"source-{source_index}")
        status = str(block.get("status") or "unknown")
        items = block.get("items") if isinstance(block.get("items"), list) else []
        source_statuses.append(
            {
                "id": source_id,
                "name": format_source_name(source_id),
                "status": status,
                "item_count": len(items),
            }
        )
        for item_index, item in enumerate(items):
            if not isinstance(item, dict):
                continue
            title = str(item.get("title") or "").strip()
            if not title:
                continue
            normalized = re.sub(r"\s+", " ", title).lower()
            if normalized in seen_titles:
                continue
            seen_titles.add(normalized)
            extra = item.get("extra") if isinstance(item.get("extra"), dict) else {}
            flattened.append(
                {
                    "source_id": source_id,
                    "source_name": format_source_name(source_id),
                    "source_rank": item_index + 1,
                    "status": status,
                    "title": title,
                    "context": str(extra.get("hover") or ""),
                    "info": str(extra.get("info") or ""),
                    "url": str(item.get("url") or ""),
                }
            )
    flattened.sort(key=lambda item: (item["source_rank"], item["source_name"].lower(), item["title"].lower()))
    return flattened[:MAX_TRENDS], source_statuses


def build_repo_shortlist(repos: list[dict[str, Any]]) -> list[dict[str, Any]]:
    excluded_terms = [
        "awesome",
        "public api",
        "public-apis",
        "curated list",
        "starter",
        "boilerplate",
        "template",
        "usecases",
    ]
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    filtered: list[dict[str, Any]] = []
    for repo in repos:
        category = str(repo.get("category") or "Other")
        if category == "Other":
            continue
        text = " ".join(
            [
                str(repo.get("full_name") or ""),
                str(repo.get("description") or ""),
                " ".join(repo.get("tags") or []),
            ]
        ).lower()
        if any(term in text for term in excluded_terms):
            continue
        filtered.append(repo)
        grouped[category].append(repo)
    selected: list[dict[str, Any]] = []
    seen: set[str] = set()
    for category in sorted(grouped.keys()):
        top_items = sorted(
            grouped[category],
            key=lambda item: int(item.get("stargazers_count") or 0),
            reverse=True,
        )[:1]
        for repo in top_items:
            full_name = str(repo.get("full_name") or "")
            if full_name and full_name not in seen:
                selected.append(repo)
                seen.add(full_name)
    for theme in REPO_THEMES:
        ranked = sorted(
            filtered,
            key=lambda item: (
                sum(
                    1
                    for keyword in theme["keywords"]
                    if keyword in " ".join(
                        [
                            str(item.get("full_name") or ""),
                            str(item.get("description") or ""),
                            " ".join(item.get("tags") or []),
                            str(item.get("category") or ""),
                        ]
                    ).lower()
                ),
                int(item.get("stargazers_count") or 0),
            ),
            reverse=True,
        )
        added = 0
        for repo in ranked:
            if added >= theme["limit"]:
                break
            full_name = str(repo.get("full_name") or "")
            if not full_name or full_name in seen:
                continue
            text = " ".join(
                [
                    full_name,
                    str(repo.get("description") or ""),
                    " ".join(repo.get("tags") or []),
                    str(repo.get("category") or ""),
                ]
            ).lower()
            score = sum(1 for keyword in theme["keywords"] if keyword in text)
            if score <= 0:
                continue
            selected.append(repo)
            seen.add(full_name)
            added += 1
    selected.sort(key=lambda item: int(item.get("stargazers_count") or 0), reverse=True)
    trimmed = selected[:MAX_REPOS]
    return [
        {
            "full_name": repo.get("full_name", ""),
            "category": repo.get("category", "Other"),
            "description": repo.get("description", ""),
            "tags": repo.get("tags") or [],
            "stargazers_count": int(repo.get("stargazers_count") or 0),
            "html_url": repo.get("html_url", ""),
        }
        for repo in trimmed
        if repo.get("full_name")
    ]


def build_llm_prompt(trends: list[dict[str, Any]], repos: list[dict[str, Any]]) -> str:
    trend_payload = [
        {
            "title": trend["title"],
            "source": trend["source_name"],
            "context": trend["context"],
            "info": trend["info"],
            "url": trend["url"],
        }
        for trend in trends
    ]
    repo_payload = [
        {
            "full_name": repo["full_name"],
            "category": repo["category"],
            "description": repo["description"],
            "tags": repo["tags"][:4],
            "stars": repo["stargazers_count"],
        }
        for repo in repos
    ]
    return (
        "Current trends:\n"
        f"{json.dumps(trend_payload, ensure_ascii=False, indent=2)}\n\n"
        "Available starred repos to combine:\n"
        f"{json.dumps(repo_payload, ensure_ascii=False, indent=2)}"
    )


def generate_ideas_with_llm(trends: list[dict[str, Any]], repos: list[dict[str, Any]], env: dict[str, str]) -> list[dict[str, Any]]:
    base_url = env["ANTHROPIC_BASE_URL"].rstrip("/")
    endpoint = f"{base_url}/v1/messages"
    payload = {
        "model": env.get("ANTHROPIC_MODEL") or env.get("ANTHROPIC_DEFAULT_SONNET_MODEL") or "MiniMax-M2.7",
        "max_tokens": 2200,
        "temperature": 0.2,
        "system": OPPORTUNITY_SYSTEM_PROMPT,
        "messages": [
            {
                "role": "user",
                "content": [{"type": "text", "text": build_llm_prompt(trends, repos)}],
            }
        ],
    }
    headers = {
        "x-api-key": env["ANTHROPIC_AUTH_TOKEN"],
        "anthropic-version": "2023-06-01",
    }
    response, _ = http_json(endpoint, headers=headers, payload=payload, timeout=45)
    content = response.get("content", [])
    text = "\n".join(
        item.get("text", "")
        for item in content
        if isinstance(item, dict) and item.get("type") == "text"
    ).strip()
    if not text:
        raise ValueError("LLM did not return text content.")
    parsed = parse_json_object(text)
    ideas = parsed.get("ideas")
    if not isinstance(ideas, list):
        raise ValueError("LLM did not return an ideas array.")
    return [idea for idea in ideas if isinstance(idea, dict)]


def first_matching_trends(trends: list[dict[str, Any]], keywords: list[str], fallback_count: int = 2) -> list[dict[str, Any]]:
    matched = [
        trend
        for trend in trends
        if any(keyword in f"{trend['title']} {trend['context']}".lower() for keyword in keywords)
    ]
    return matched[:fallback_count] or trends[:fallback_count]


def pick_repo_group(repos: list[dict[str, Any]], categories: list[str], limit: int = 3) -> list[dict[str, Any]]:
    selected = [repo for repo in repos if repo["category"] in categories]
    return selected[:limit]


def pick_repos_by_keywords(repos: list[dict[str, Any]], keywords: list[str], limit: int = 3) -> list[dict[str, Any]]:
    ranked = sorted(
        repos,
        key=lambda repo: (
            sum(
                1
                for keyword in keywords
                if keyword in " ".join(
                    [
                        repo["full_name"],
                        repo["category"],
                        repo["description"],
                        " ".join(repo["tags"]),
                    ]
                ).lower()
            ),
            repo["stargazers_count"],
        ),
        reverse=True,
    )
    return [repo for repo in ranked if any(keyword in f"{repo['full_name']} {repo['category']} {repo['description']} {' '.join(repo['tags'])}".lower() for keyword in keywords)][:limit]


def fallback_ideas(trends: list[dict[str, Any]], repos: list[dict[str, Any]]) -> list[dict[str, Any]]:
    blueprints = [
        {
            "name": "Trend-to-SEO Audit Bot",
            "summary": "Turn hot topics into landing-page audits and quick-win content briefs for indie brands.",
            "why_now": "Search visibility keeps shifting toward AI-assisted discovery, and live trend changes create short windows for ranking and distribution.",
            "revenue_model": "Monthly subscription for audit credits plus white-label agency reports.",
            "build_plan": ["Watch trend feeds", "Crawl target sites", "Generate audit briefs and outreach lists"],
            "trends": [trend["title"] for trend in first_matching_trends(trends, ["seo", "ai", "search", "agent", "brand"])],
            "repos": [repo["full_name"] for repo in pick_repos_by_keywords(repos, ["seo", "geo", "crawl", "scrap", "audit", "ranking"])],
            "category_focus": ["SEO & Marketing", "Web Scraping & Browser Automation"],
            "confidence": "medium",
        },
        {
            "name": "AI Coding Ops Inbox",
            "summary": "Bundle coding-agent workflows, remote alerts, and code intelligence into a lightweight team command center.",
            "why_now": "Coding agents are spreading quickly, but teams still lack simple visibility and control over parallel AI work.",
            "revenue_model": "Per-seat SaaS for agencies and small dev teams.",
            "build_plan": ["Connect agent tools", "Track tasks and alerts", "Sell team dashboards and automations"],
            "trends": [trend["title"] for trend in first_matching_trends(trends, ["github", "agent", "ai", "developer", "hackernews"])],
            "repos": [repo["full_name"] for repo in pick_repos_by_keywords(repos, ["claude code", "codex", "cursor", "coding agent", "developer", "agent"])],
            "category_focus": ["AI Coding Tools", "Developer Tools"],
            "confidence": "medium",
        },
        {
            "name": "Viral Content Repurposer",
            "summary": "Convert live hot topics into social assets, explainers, and landing pages for creators or micro-brands.",
            "why_now": "Trend windows are short, and creators need fast production pipelines that package text, images, and pages together.",
            "revenue_model": "Subscription for content packs or done-for-you service retainers.",
            "build_plan": ["Ingest trends", "Generate media assets", "Publish channel-ready packages"],
            "trends": [trend["title"] for trend in first_matching_trends(trends, ["video", "iphone", "douyin", "weibo", "bilibili"])],
            "repos": [repo["full_name"] for repo in pick_repos_by_keywords(repos, ["video", "voice", "audio", "image", "content", "landing"])],
            "category_focus": ["AI Content & Media", "Web Development"],
            "confidence": "medium",
        },
        {
            "name": "Market Pulse Research Terminal",
            "summary": "Track retail market narratives and turn them into niche trading or business-intelligence alerts.",
            "why_now": "Finance chatter and macro headlines move fast, and solo operators need opinionated tools instead of generic news dashboards.",
            "revenue_model": "Paid newsletter, premium alerts, or analyst dashboards.",
            "build_plan": ["Monitor hot finance topics", "Score market signals", "Ship alerts and research summaries"],
            "trends": [trend["title"] for trend in first_matching_trends(trends, ["stock", "finance", "market", "wallstreet", "xueqiu"])],
            "repos": [repo["full_name"] for repo in pick_repos_by_keywords(repos, ["trading", "finance", "quant", "market", "research", "stock"])],
            "category_focus": ["Finance & Trading", "Data & Analytics"],
            "confidence": "medium",
        },
    ]
    return blueprints


def sanitize_idea(
    idea: dict[str, Any],
    repo_lookup: dict[str, dict[str, Any]],
    repo_shortlist: list[dict[str, Any]],
    trend_titles: set[str],
    available_trends: list[dict[str, Any]],
) -> dict[str, Any]:
    repo_names = [name for name in idea.get("repos", []) if isinstance(name, str) and name in repo_lookup]
    selected_trends = [title for title in idea.get("trends", []) if isinstance(title, str) and title in trend_titles]
    build_plan = [str(step).strip() for step in idea.get("build_plan", []) if str(step).strip()][:3]
    category_focus = [str(label).strip() for label in idea.get("category_focus", []) if str(label).strip()][:3]
    if len(repo_names) < 2:
        supplemental = [
            repo["full_name"]
            for repo in repo_shortlist
            if repo["full_name"] not in repo_names
            and (not category_focus or repo["category"] in category_focus)
        ]
        repo_names.extend(supplemental[: 2 - len(repo_names)])
    if not selected_trends and available_trends:
        selected_trends = [available_trends[0]["title"]]
    return {
        "name": str(idea.get("name") or "Untitled Opportunity").strip(),
        "summary": str(idea.get("summary") or "").strip(),
        "why_now": str(idea.get("why_now") or "").strip(),
        "revenue_model": str(idea.get("revenue_model") or "").strip(),
        "build_plan": build_plan or ["Select a narrow niche", "Assemble the repo stack", "Ship a paid MVP"],
        "trends": selected_trends,
        "repos": repo_names,
        "category_focus": category_focus,
        "confidence": str(idea.get("confidence") or "medium").strip().lower(),
    }


def keyword_tokens(text: str) -> set[str]:
    raw_tokens = re.findall(r"[a-z0-9][a-z0-9\-\+]{2,}", text.lower())
    stop_words = {
        "with",
        "from",
        "into",
        "that",
        "this",
        "your",
        "their",
        "about",
        "there",
        "which",
        "while",
        "where",
        "daily",
        "today",
        "using",
        "build",
        "launch",
        "trend",
        "trends",
        "ideas",
        "idea",
        "project",
        "projects",
        "repo",
        "repos",
    }
    return {token for token in raw_tokens if token not in stop_words}


def clamp_score(value: int) -> int:
    return max(0, min(100, value))


def compute_trend_repo_match_score(
    idea: dict[str, Any],
    repo_details: list[dict[str, Any]],
    trend_details: list[dict[str, Any]],
) -> int:
    trend_text = " ".join(
        f"{trend.get('title', '')} {trend.get('context', '')} {trend.get('info', '')}"
        for trend in trend_details
    )
    repo_text = " ".join(
        f"{repo.get('full_name', '')} {repo.get('category', '')} {repo.get('description', '')} {' '.join(repo.get('tags', []))}"
        for repo in repo_details
    )
    trend_tokens = keyword_tokens(trend_text)
    repo_tokens = keyword_tokens(repo_text)
    overlap = len(trend_tokens & repo_tokens)
    coverage = len(idea.get("trends", [])) * 5 + len(repo_details) * 6
    confidence_bonus = {"high": 10, "medium": 4, "low": 0}.get(str(idea.get("confidence") or "medium"), 0)
    return clamp_score(38 + overlap * 10 + coverage + confidence_bonus)


def compute_revenue_score(idea: dict[str, Any], repo_details: list[dict[str, Any]]) -> int:
    text = " ".join(
        [
            str(idea.get("summary") or ""),
            str(idea.get("why_now") or ""),
            str(idea.get("revenue_model") or ""),
            " ".join(str(step) for step in idea.get("build_plan", [])),
            " ".join(repo.get("category", "") for repo in repo_details),
        ]
    ).lower()
    strong_terms = ["subscription", "saas", "b2b", "credits", "white-label", "api", "platform", "dashboard"]
    medium_terms = ["alerts", "audit", "monitor", "newsletter", "marketplace", "data", "teams", "agency"]
    score = 34
    score += sum(10 for term in strong_terms if term in text)
    score += sum(6 for term in medium_terms if term in text)
    score += min(len(repo_details), 4) * 4
    score += {"high": 10, "medium": 4, "low": 0}.get(str(idea.get("confidence") or "medium"), 0)
    return clamp_score(score)


def compute_niche_difficulty_score(
    idea: dict[str, Any],
    repo_details: list[dict[str, Any]],
    trend_details: list[dict[str, Any]],
) -> int:
    text = " ".join(
        [
            str(idea.get("summary") or ""),
            str(idea.get("why_now") or ""),
            str(idea.get("revenue_model") or ""),
            " ".join(repo.get("category", "") for repo in repo_details),
            " ".join(f"{trend.get('title', '')} {trend.get('context', '')}" for trend in trend_details),
        ]
    ).lower()
    hard_terms = ["security", "trading", "finance", "health", "legal", "compliance", "enterprise", "platform", "marketplace"]
    medium_terms = ["team", "workflow", "data", "analytics", "monitor", "research", "developer"]
    easy_terms = ["audit", "brief", "content", "alert", "landing", "newsletter", "directory", "report"]
    difficulty = 42
    difficulty += sum(9 for term in hard_terms if term in text)
    difficulty += sum(5 for term in medium_terms if term in text)
    difficulty -= sum(6 for term in easy_terms if term in text)
    difficulty += max(0, len(repo_details) - 2) * 4
    difficulty += max(0, len(trend_details) - 2) * 2
    return clamp_score(difficulty)


def compute_build_speed_score(idea: dict[str, Any], repo_details: list[dict[str, Any]]) -> int:
    text = " ".join(
        [
            str(idea.get("summary") or ""),
            str(idea.get("why_now") or ""),
            str(idea.get("revenue_model") or ""),
            " ".join(str(step) for step in idea.get("build_plan", [])),
            " ".join(repo.get("category", "") for repo in repo_details),
        ]
    ).lower()
    fast_terms = ["audit", "alert", "brief", "dashboard", "newsletter", "monitor", "report", "content", "landing"]
    slow_terms = ["marketplace", "platform", "trading", "security", "video", "agent", "infrastructure", "real-time"]
    score = 56
    score += sum(7 for term in fast_terms if term in text)
    score -= sum(6 for term in slow_terms if term in text)
    score -= max(0, len(repo_details) - 2) * 4
    return clamp_score(score)


def compute_monetization_latency_score(idea: dict[str, Any], repo_details: list[dict[str, Any]]) -> int:
    text = " ".join(
        [
            str(idea.get("summary") or ""),
            str(idea.get("revenue_model") or ""),
            " ".join(repo.get("category", "") for repo in repo_details),
        ]
    ).lower()
    fast_terms = ["b2b", "subscription", "white-label", "agency", "audit", "service", "credits", "newsletter", "alerts"]
    slow_terms = ["ads", "marketplace", "consumer", "creator", "community", "media", "platform"]
    score = 50
    score += sum(8 for term in fast_terms if term in text)
    score -= sum(7 for term in slow_terms if term in text)
    return clamp_score(score)


def compute_recurring_revenue_score(idea: dict[str, Any], repo_details: list[dict[str, Any]]) -> int:
    text = " ".join(
        [
            str(idea.get("summary") or ""),
            str(idea.get("revenue_model") or ""),
            " ".join(repo.get("category", "") for repo in repo_details),
        ]
    ).lower()
    recurring_terms = ["subscription", "saas", "retainer", "dashboard", "monitor", "alerts", "data", "b2b", "platform"]
    one_off_terms = ["commission", "affiliate", "ad", "sponsorship", "one-time", "template"]
    score = 46
    score += sum(8 for term in recurring_terms if term in text)
    score -= sum(7 for term in one_off_terms if term in text)
    return clamp_score(score)


def compute_founder_score(
    niche_difficulty_score: int,
    build_speed_score: int,
    monetization_latency_score: int,
    recurring_revenue_score: int,
    trend_repo_match_score: int,
    revenue_score: int,
) -> int:
    difficulty_tailwind = 100 - niche_difficulty_score
    weighted = (
        difficulty_tailwind * 0.22
        + build_speed_score * 0.22
        + monetization_latency_score * 0.22
        + recurring_revenue_score * 0.18
        + trend_repo_match_score * 0.08
        + revenue_score * 0.08
    )
    return clamp_score(round(weighted))


def score_explanations(idea: dict[str, Any]) -> dict[str, str]:
    strengths = [
        ("build_speed_score", "It looks shippable as a narrow first release."),
        ("monetization_latency_score", "The revenue path can start early without waiting for scale."),
        ("recurring_revenue_score", "The usage pattern supports repeatable monthly value."),
        ("trend_repo_match_score", "The trend signal and repo stack already line up."),
        ("revenue_score", "The pricing surface is visible from day one."),
        ("niche_difficulty_score", "The niche is constrained enough for a focused wedge."),
    ]
    weaknesses = [
        ("niche_difficulty_score", "The niche carries trust, workflow, or compliance weight."),
        ("build_speed_score", "The MVP scope is still heavier than a fast founder build."),
        ("monetization_latency_score", "Value may be obvious before willingness to pay is."),
        ("recurring_revenue_score", "The business model risks looking one-off instead of compounding."),
        ("trend_repo_match_score", "The repo stack is not yet tightly matched to the trend."),
        ("revenue_score", "Pricing is present, but not sharp enough yet."),
    ]
    best_metric = max(
        strengths,
        key=lambda item: 100 - idea[item[0]] if item[0] == "niche_difficulty_score" else idea[item[0]],
    )
    worst_metric = min(
        weaknesses,
        key=lambda item: 100 - idea[item[0]] if item[0] == "niche_difficulty_score" else idea[item[0]],
    )
    return {
        "best_part": best_metric[1],
        "biggest_risk": worst_metric[1],
    }


def build_penalties(idea: dict[str, Any]) -> list[str]:
    penalties: list[str] = []
    if idea["niche_difficulty_score"] >= 68:
        penalties.append("High-trust niche increases validation and delivery burden.")
    if idea["build_speed_score"] <= 56:
        penalties.append("Current MVP shape is too broad for a fast solo launch.")
    if idea["monetization_latency_score"] <= 56:
        penalties.append("Revenue likely arrives after proof, not at first contact.")
    if idea["recurring_revenue_score"] <= 56:
        penalties.append("Retention loop is weak, so monthly revenue is less certain.")
    if idea["trend_repo_match_score"] <= 58:
        penalties.append("Trend signal and repo stack are only loosely connected.")
    if idea["revenue_score"] <= 62:
        penalties.append("Packaging still needs a sharper buyer and price point.")
    return penalties[:3]


def fastest_mvp(idea: dict[str, Any]) -> str:
    first_step = next((str(step).strip() for step in idea.get("build_plan", []) if str(step).strip()), "")
    if first_step:
        return f"Ship only the first wedge: {first_step}."
    if idea.get("trends"):
        return f"Start with a manual signal digest around {idea['trends'][0]}."
    return "Start with one narrow workflow and one paying user before expanding."


def likely_first_customer(idea: dict[str, Any], repo_details: list[dict[str, Any]]) -> str:
    text = " ".join(
        [
            str(idea.get("summary") or ""),
            str(idea.get("why_now") or ""),
            str(idea.get("revenue_model") or ""),
            " ".join(repo.get("category", "") for repo in repo_details),
        ]
    ).lower()
    customer_map = [
        ("security", "Security teams at software companies"),
        ("devsecops", "Engineering teams that own CI and dependency hygiene"),
        ("content", "Content platforms with moderation and rights risk"),
        ("copyright", "Media platforms and rights management teams"),
        ("finance", "Operators who react to live market or risk data"),
        ("trading", "Independent traders and small market intelligence desks"),
        ("agri", "Agricultural traders, cooperatives, and food operators"),
        ("agency", "Agencies packaging monitoring or audits for clients"),
        ("creator", "Creators and solo operators who need lightweight tooling"),
        ("dashboard", "Operators who already live inside recurring dashboards"),
    ]
    for term, customer in customer_map:
        if term in text:
            return customer
    return "Small teams with an urgent workflow and budget to pay for speed."


def improvement_actions(idea: dict[str, Any]) -> list[str]:
    priorities = [
        ("niche_difficulty_score", idea["niche_difficulty_score"]),
        ("build_speed_score", 100 - idea["build_speed_score"]),
        ("monetization_latency_score", 100 - idea["monetization_latency_score"]),
        ("recurring_revenue_score", 100 - idea["recurring_revenue_score"]),
        ("trend_repo_match_score", 100 - idea["trend_repo_match_score"]),
    ]
    ordered = [name for name, _ in sorted(priorities, key=lambda item: item[1], reverse=True)]
    actions: list[str] = []
    for name in ordered:
        if name == "niche_difficulty_score":
            actions.append("Narrow the buyer to one painful workflow and one high-urgency trigger.")
        elif name == "build_speed_score":
            actions.append(fastest_mvp(idea))
        elif name == "monetization_latency_score":
            actions.append("Sell the first version as a done-for-you service before broadening into product.")
        elif name == "recurring_revenue_score":
            actions.append("Add a recurring alert, report, or compliance loop so usage repeats monthly.")
        elif name == "trend_repo_match_score":
            actions.append("Swap one generic repo dependency for tooling that matches the active trend more directly.")
        if len(actions) == 2:
            break
    return actions


def founder_memo(
    idea: dict[str, Any],
    repo_details: list[dict[str, Any]],
) -> dict[str, Any]:
    explanations = score_explanations(idea)
    penalties = build_penalties(idea)
    improvements = improvement_actions(idea)
    why_high = " ".join(
        part
        for part in [
            explanations["best_part"],
            "The score rises when it can ship, charge, and repeat without needing heavy scale."
            if idea["founder_score"] >= 60
            else "",
        ]
        if part
    )
    why_low = " ".join(
        part
        for part in [
            explanations["biggest_risk"],
            penalties[0] if penalties else "",
        ]
        if part
    )
    return {
        "best_part": explanations["best_part"],
        "biggest_risk": explanations["biggest_risk"],
        "fastest_mvp": fastest_mvp(idea),
        "first_customer": likely_first_customer(idea, repo_details),
        "why_high": why_high,
        "why_low": why_low,
        "top_penalties": penalties,
        "improve_next": improvements,
    }


def classify_build_decision(idea: dict[str, Any], memo: dict[str, Any]) -> dict[str, str]:
    if (
        idea["founder_score"] >= 62
        and idea["build_speed_score"] >= 60
        and idea["monetization_latency_score"] >= 58
        and idea["niche_difficulty_score"] <= 62
    ):
        return {
            "label": "Build now",
            "tone": "good",
            "summary": memo["best_part"],
        }
    if (
        idea["founder_score"] >= 48
        and idea["opportunity_score"] >= 52
        and idea["trend_repo_match_score"] >= 50
    ):
        return {
            "label": "Validate first",
            "tone": "caution",
            "summary": memo["biggest_risk"],
        }
    return {
        "label": "Avoid for now",
        "tone": "warning",
        "summary": memo["biggest_risk"],
    }


def enrich_ideas(
    ideas: list[dict[str, Any]],
    repo_lookup: dict[str, dict[str, Any]],
    trends: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    trend_lookup = {trend["title"]: trend for trend in trends}
    enriched: list[dict[str, Any]] = []
    for idea in ideas:
        repo_details = [
            {
                "full_name": repo_name,
                "html_url": repo_lookup[repo_name]["html_url"],
                "category": repo_lookup[repo_name]["category"],
                "description": repo_lookup[repo_name]["description"],
                "stars": repo_lookup[repo_name]["stargazers_count"],
                "tags": repo_lookup[repo_name]["tags"],
            }
            for repo_name in idea["repos"]
            if repo_name in repo_lookup
        ]
        trend_details = [trend_lookup[title] for title in idea["trends"] if title in trend_lookup]
        match_score = compute_trend_repo_match_score(idea, repo_details, trend_details)
        revenue_score = compute_revenue_score(idea, repo_details)
        niche_difficulty_score = compute_niche_difficulty_score(idea, repo_details, trend_details)
        build_speed_score = compute_build_speed_score(idea, repo_details)
        monetization_latency_score = compute_monetization_latency_score(idea, repo_details)
        recurring_revenue_score = compute_recurring_revenue_score(idea, repo_details)
        founder_score = compute_founder_score(
            niche_difficulty_score,
            build_speed_score,
            monetization_latency_score,
            recurring_revenue_score,
            match_score,
            revenue_score,
        )
        opportunity_score = clamp_score(round(revenue_score * 0.35 + match_score * 0.25 + founder_score * 0.4))
        idea_metrics = {
            **idea,
            "trend_repo_match_score": match_score,
            "revenue_score": revenue_score,
            "niche_difficulty_score": niche_difficulty_score,
            "build_speed_score": build_speed_score,
            "monetization_latency_score": monetization_latency_score,
            "recurring_revenue_score": recurring_revenue_score,
            "founder_score": founder_score,
            "opportunity_score": opportunity_score,
        }
        memo = founder_memo(idea_metrics, repo_details)
        build_decision = classify_build_decision(idea_metrics, memo)
        enriched.append(
            {
                **idea_metrics,
                "repo_details": repo_details,
                "trend_details": trend_details,
                "founder_memo": memo,
                "build_decision": build_decision,
            }
        )
    return sorted(
        enriched,
        key=lambda item: (item["founder_score"], item["opportunity_score"], item["revenue_score"]),
        reverse=True,
    )


def render_report(
    report_date: str,
    generated_at: str,
    source_statuses: list[dict[str, Any]],
    trends: list[dict[str, Any]],
    ideas: list[dict[str, Any]],
    repo_lookup: dict[str, dict[str, Any]],
    generation_mode: str,
) -> str:
    lines = [
        f"# Opportunity Radar - {report_date}",
        "",
        f"Generated at: {generated_at}",
        f"Trend source: {NEWSNOW_ENDPOINT}",
        f"Star repo source: stars_cache.json",
        f"Mode: {generation_mode}",
        "",
        "## Source Health",
        "",
    ]
    for source in source_statuses:
        lines.append(f"- {source['name']} — {source['status']} ({source['item_count']} items)")
    lines.extend(["", "## Trend Snapshot", ""])
    for trend in trends:
        detail = trend["context"] or trend["info"] or "No extra context."
        lines.append(f"- [{trend['title']}]({trend['url']}) — {trend['source_name']} | {detail}")
    lines.extend(["", "## Project Ideas", ""])
    for idea in ideas:
        lines.append(f"### {idea['name']}")
        if idea["summary"]:
            lines.append(idea["summary"])
        if idea["trends"]:
            lines.append(f"Signals: {', '.join(idea['trends'])}")
        if idea["repos"]:
            repo_links = ", ".join(f"[{name}]({repo_lookup[name]['html_url']})" for name in idea["repos"] if name in repo_lookup)
            lines.append(f"Repo stack: {repo_links}")
        if idea["category_focus"]:
            lines.append(f"Category focus: {', '.join(idea['category_focus'])}")
        if idea["why_now"]:
            lines.append(f"Why now: {idea['why_now']}")
        if idea["revenue_model"]:
            lines.append(f"Revenue path: {idea['revenue_model']}")
        if idea["build_plan"]:
            lines.append(f"Launch path: {' -> '.join(idea['build_plan'])}")
        lines.append(
            "Founder score: "
            f"{idea['founder_score']} | "
            f"Difficulty {idea['niche_difficulty_score']} | "
            f"Build speed {idea['build_speed_score']} | "
            f"Monetization {idea['monetization_latency_score']} | "
            f"Recurring {idea['recurring_revenue_score']}"
        )
        lines.append(
            "Signal score: "
            f"Radar {idea['opportunity_score']} | Revenue {idea['revenue_score']} | Fit {idea['trend_repo_match_score']}"
        )
        founder_memo_payload = idea.get("founder_memo", {})
        build_decision = idea.get("build_decision", {})
        if build_decision:
            lines.append(
                f"Decision: {build_decision.get('label', '')} — {build_decision.get('summary', '')}"
            )
        if founder_memo_payload:
            lines.append(f"Best part: {founder_memo_payload.get('best_part', '')}")
            lines.append(f"Biggest risk: {founder_memo_payload.get('biggest_risk', '')}")
            lines.append(f"Fastest MVP: {founder_memo_payload.get('fastest_mvp', '')}")
            lines.append(f"Likely first customer: {founder_memo_payload.get('first_customer', '')}")
            lines.append(f"Why this scores high: {founder_memo_payload.get('why_high', '')}")
            lines.append(f"What drags it down: {founder_memo_payload.get('why_low', '')}")
            penalties = founder_memo_payload.get("top_penalties", [])
            if penalties:
                lines.append(f"Top penalties: {' | '.join(penalties)}")
            improvements = founder_memo_payload.get("improve_next", [])
            if improvements:
                lines.append(f"Improve next: {' | '.join(improvements)}")
        lines.append(f"Confidence: {idea['confidence']}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def build_site_payload(
    report_date: str,
    generated_at: str,
    source_statuses: list[dict[str, Any]],
    trends: list[dict[str, Any]],
    ideas: list[dict[str, Any]],
    generation_mode: str,
) -> dict[str, Any]:
    categories = sorted(
        {
            repo["category"]
            for idea in ideas
            for repo in idea.get("repo_details", [])
            if repo.get("category")
        }
        | {category for idea in ideas for category in idea.get("category_focus", []) if category}
    )
    return {
        "date": report_date,
        "generated_at": generated_at,
        "trend_source": NEWSNOW_ENDPOINT,
        "star_repo_source": "stars_cache.json",
        "mode": generation_mode,
        "available_categories": categories,
        "source_health": source_statuses,
        "trends": trends,
        "ideas": ideas,
    }


def write_site_data(site_dir: Path, payload: dict[str, Any], markdown_report: str) -> tuple[Path, Path]:
    data_dir = site_dir / "data"
    reports_dir = data_dir / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    site_reports_dir = site_dir / "reports"
    site_reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / f"{payload['date']}.json"
    save_json_file(report_path, payload)
    markdown_path = site_reports_dir / f"{payload['date']}.md"
    markdown_path.write_text(markdown_report, encoding="utf-8")

    report_files = sorted(reports_dir.glob("*.json"), reverse=True)
    reports_index = []
    for file_path in report_files:
        report_payload = load_json_file(file_path, {})
        if not isinstance(report_payload, dict):
            continue
        reports_index.append(
            {
                "date": report_payload.get("date", file_path.stem),
                "generated_at": report_payload.get("generated_at", ""),
                "mode": report_payload.get("mode", ""),
                "idea_count": len(report_payload.get("ideas", [])) if isinstance(report_payload.get("ideas"), list) else 0,
                "trend_count": len(report_payload.get("trends", [])) if isinstance(report_payload.get("trends"), list) else 0,
                "path": f"data/reports/{file_path.name}",
                "top_idea": (
                    report_payload.get("ideas", [{}])[0].get("name", "")
                    if isinstance(report_payload.get("ideas"), list) and report_payload.get("ideas")
                    else ""
                ),
                "top_revenue_score": (
                    report_payload.get("ideas", [{}])[0].get("revenue_score", 0)
                    if isinstance(report_payload.get("ideas"), list) and report_payload.get("ideas")
                    else 0
                ),
                "top_founder_score": (
                    report_payload.get("ideas", [{}])[0].get("founder_score", 0)
                    if isinstance(report_payload.get("ideas"), list) and report_payload.get("ideas")
                    else 0
                ),
            }
        )
    index_payload = {
        "generated_at": payload["generated_at"],
        "latest": payload["date"],
        "reports": reports_index,
    }
    index_path = data_dir / "index.json"
    save_json_file(index_path, index_payload)
    latest_path = data_dir / "latest.json"
    save_json_file(latest_path, payload)
    return report_path, index_path


def main() -> int:
    args = parse_args()
    root = Path.cwd()
    config_path = resolve_path(root, args.config)
    cache_path = resolve_path(root, args.cache)
    output_dir = resolve_path(root, args.output_dir)
    site_dir = resolve_path(root, args.site_dir)
    report_date = args.date or utc_today()
    output_dir.mkdir(parents=True, exist_ok=True)

    repos = load_starred_repos(cache_path)
    repo_shortlist = build_repo_shortlist(repos)
    repo_lookup = {repo["full_name"]: repo for repo in repo_shortlist}
    trends_payload = fetch_newsnow_payload()
    trends, source_statuses = dedupe_trends(trends_payload)
    generation_mode = "live-with-llm"

    try:
        env = read_minimax_env(config_path)
    except Exception:
        env = {}
        generation_mode = "live-with-deterministic-ideas"

    try:
        if not env:
            raise ValueError("Missing LLM configuration.")
        idea_candidates = generate_ideas_with_llm(trends, repo_shortlist, env)
    except Exception:
        idea_candidates = fallback_ideas(trends, repo_shortlist)
        generation_mode = "live-with-deterministic-ideas"

    trend_titles = {trend["title"] for trend in trends}
    ideas = [sanitize_idea(idea, repo_lookup, repo_shortlist, trend_titles, trends) for idea in idea_candidates][:4]
    if not ideas:
        ideas = [sanitize_idea(idea, repo_lookup, repo_shortlist, trend_titles, trends) for idea in fallback_ideas(trends, repo_shortlist)]
        generation_mode = "live-with-deterministic-ideas"
    ideas = enrich_ideas(ideas, repo_lookup, trends)

    generated_at = utc_now()
    report = render_report(report_date, generated_at, source_statuses, trends, ideas, repo_lookup, generation_mode)
    output_path = output_dir / f"{report_date}.md"
    output_path.write_text(report, encoding="utf-8")
    site_payload = build_site_payload(report_date, generated_at, source_statuses, trends, ideas, generation_mode)
    site_report_path, site_index_path = write_site_data(site_dir, site_payload, report)

    print(f"Generated {output_path}")
    print(f"Generated {site_report_path}")
    print(f"Updated {site_index_path}")
    print(f"Trends analyzed: {len(trends)}")
    print(f"Starred repos considered: {len(repo_shortlist)}")
    print(f"Ideas generated: {len(ideas)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
